"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "en" | "ar";

const dict: Record<Lang, Record<string, string>> = {
  en: {
    navModules: "Modules",
    navWhy: "Why Nxentra",
    navHow: "How it works",
    navPricing: "Pricing",
    navContact: "Contact",
    ctaTry: "Start free",
    ctaLiveDemo: "Try live demo",
    demoCredentials: "Demo login — Email: demo@nxentra.com · Password: demo1234",
    ctaDemo: "Watch demo",
    heroTag: "Commerce accounting, automated",
    heroH1a: "Your Shopify store deserves",
    heroH1b: "real accounting.",
    heroSub: "Nxentra connects your Shopify, Stripe, POS, and bank feeds into one financial truth. Auto-reconciled. Multi-currency. Audit-ready from day one.",
    trustFree: "Free to start",
    trustNoCard: "Event-sourced audit trail",
    trustSetup: "Your data, fully exportable",
    liveOn: "Live on",
    // Shopify Spotlight
    shopifyBadge: "Shopify Integration",
    shopifyH2a: "Selling on Shopify?",
    shopifyH2b: "Your accounting is already done.",
    shopifyDesc: "Every Shopify order, refund, discount, tax, and payout automatically becomes a proper double-entry journal entry. COGS calculated at weighted average cost. Multi-currency conversions handled. Inventory levels synced in real-time.",
    shopifyBullet1: "Orders auto-post to Sales, AR, Tax, and Inventory accounts",
    shopifyBullet2: "Shopify payouts reconcile against bank deposits automatically",
    shopifyBullet3: "Refunds create proper reversal entries — no manual corrections",
    shopifyBullet4: "Multi-currency orders converted at transaction-date rates",
    shopifyCta: "Connect your Shopify store",
    shopifyFlow1Label: "Shopify Order #1042",
    shopifyFlow1Sub: "3 items · $287.50 · USD",
    shopifyFlow2Label: "Ingestion Engine",
    shopifyFlow2Sub: "Normalize → Map accounts → Validate",
    shopifyFlow3Label: "Journal Entry JE-1-000847",
    shopifyFlow3Sub: "DR Accounts Receivable $287.50 · CR Sales $250.00 · CR Tax $37.50",
    shopifyFlow4Label: "Auto-Reconciled",
    shopifyFlow4Sub: "Matched with Shopify Payout #P-2891",
    // Modules
    modulesTitle: "One platform. Every module.",
    modulesSub: "Stop stitching together disconnected tools. Nxentra gives you a complete operating system for your business.",
    modAccounting: "Accounting",
    modAccountingDesc: "GL, chart of accounts, journal entries, multi-currency, bank reconciliation",
    modSales: "Sales & Invoicing",
    modSalesDesc: "Invoices, tax codes, posting profiles, customer receipts, AR aging",
    modInventory: "Inventory",
    modInventoryDesc: "Warehouses, stock balances, COGS tracking, weighted average costing",
    modPurchases: "Purchases",
    modPurchasesDesc: "Purchase bills, vendor payments, AP aging, multi-currency payables",
    modProperties: "Properties",
    modPropertiesDesc: "Unit management, lease contracts, rent collection, tenant accounting",
    modClinic: "Clinic",
    modClinicDesc: "Patient billing, appointment revenue, insurance claims, medical AR",
    modShopify: "Shopify Sync",
    modShopifyDesc: "Auto-ingest orders, refunds, and payouts. Real-time financial mapping.",
    modStripe: "Stripe Connect",
    modStripeDesc: "Payment reconciliation, fee tracking, payout matching, multi-currency",
    // Why Nxentra
    whyTitle: "Why teams switch to Nxentra",
    whySub: "Built different from legacy ERPs. Every transaction is an immutable event. Every report is derived, never manually fixed.",
    why1Title: "Universal Ingestion Engine",
    why1Desc: "Every order, payment, refund, and payout from any source becomes an immutable financial event. Shopify, Stripe, POS, bank feeds — all normalized into one ledger. No CSV imports. No manual entry. No data drift.",
    why2Title: "Auto-Reconciliation Engine",
    why2Desc: "Nxentra matches transactions across sources automatically. Bank payouts reconcile against Shopify orders. Stripe fees match journal entries. Discrepancies surface instantly — not at month-end when it's too late.",
    why3Title: "Immutable Audit Trail",
    why3Desc: "Every number on every report traces back to a source event. Nothing is manually edited. Nothing is overwritten. Your books aren't just accurate — they're provably accurate. Auditors love this.",
    why4Title: "Multi-Currency Native",
    why4Desc: "EGP, USD, SAR, EUR — all in one ledger. Automatic exchange rate lookups, currency revaluation, and unrealized gain/loss tracking. Built for businesses that operate across borders.",
    // How It Works
    howTitle: "How it works",
    howSub: "Three steps. Five minutes. Done.",
    eng1Label: "Step 1",
    eng1Title: "Connect your Shopify store",
    eng1Desc: "One click to connect. Nxentra imports your orders, refunds, payouts, and products automatically. No CSV uploads. No manual entry.",
    eng2Label: "Step 2",
    eng2Title: "We create your journal entries",
    eng2Desc: "Every order becomes a proper double-entry journal entry. Sales, tax, fees, and inventory — all mapped to your chart of accounts automatically.",
    eng3Label: "Step 3",
    eng3Title: "Reconcile payouts instantly",
    eng3Desc: "See exactly how Shopify payouts match your bank deposits. Three-column view: orders vs payouts vs bank. Discrepancies flagged instantly.",
    // Video
    videoTitle: "See Nxentra in action",
    videoSub: "Watch how Nxentra turns disconnected data into financial clarity.",
    // Dashboard Charts
    chartsTitle: "Real-time financial visibility",
    chartsSub: "Every chart is derived from live events. Revenue, expenses, cash flow, and reconciliation rates update as transactions flow in.",
    // Stats
    statModules: "Modules",
    statCurrencies: "Currencies supported",
    statEngines: "Core engines",
    statSetup: "Setup time",
    // Pricing
    pricingTitle: "Simple, transparent pricing",
    pricingSub: "Start free. Upgrade when you grow. No hidden fees.",
    pricingStarterName: "Starter",
    pricingStarterPrice: "$29",
    pricingStarterPeriod: "/month",
    pricingStarterDesc: "For solo Shopify merchants",
    pricingStarterF1: "1 Shopify store",
    pricingStarterF2: "Core accounting & GL",
    pricingStarterF3: "Bank reconciliation",
    pricingStarterF4: "1 user",
    pricingStarterF5: "Email support",
    pricingStarterCta: "Start free",
    pricingGrowthName: "Growth",
    pricingGrowthPrice: "$79",
    pricingGrowthPeriod: "/month",
    pricingGrowthDesc: "For growing merchants",
    pricingGrowthBadge: "Most popular",
    pricingGrowthF1: "3 Shopify stores",
    pricingGrowthF2: "Multi-currency support",
    pricingGrowthF3: "Commerce reconciliation",
    pricingGrowthF4: "5 users",
    pricingGrowthF5: "Priority support",
    pricingGrowthF6: "API access",
    pricingGrowthCta: "Start free",
    pricingProName: "Professional",
    pricingProPrice: "$149",
    pricingProPeriod: "/month",
    pricingProDesc: "For multi-store operators",
    pricingProF1: "Unlimited stores",
    pricingProF2: "Stripe + Shopify",
    pricingProF3: "Advanced reporting",
    pricingProF4: "15 users",
    pricingProF5: "Dedicated support",
    pricingProF6: "Custom integrations",
    pricingProCta: "Contact us",
    pricingFreeNote: "All plans include a 14-day free trial. No credit card required.",
    // Trust / Security
    trustTitle: "Bank-grade security. Built in.",
    trustSub: "Your financial data deserves the highest level of protection. Nxentra is built with security as a foundation, not an afterthought.",
    trustSec1Title: "Immutable audit trail",
    trustSec1Desc: "Every transaction is an append-only event. Nothing is overwritten or deleted.",
    trustSec2Title: "Tenant data isolation",
    trustSec2Desc: "Each company gets its own isolated database. Your data never mixes with others.",
    trustSec3Title: "HTTPS everywhere",
    trustSec3Desc: "TLS encryption in transit, HSTS preloading, and strict Content Security Policy.",
    trustSec4Title: "Your data, exportable",
    trustSec4Desc: "Full data export anytime. No vendor lock-in. You own your financial records.",
    trustSec5Title: "Role-based access",
    trustSec5Desc: "Granular permissions per user. Owner, Admin, User, and Viewer roles.",
    trustSec6Title: "Structured audit logging",
    trustSec6Desc: "Every API call, login, and data change is logged with timestamps and user context. Built for compliance from day one.",
    // Social proof
    proofTitle: "Built for merchants who demand accuracy",
    proofSub: "Early-access merchants across the Middle East and beyond are already using Nxentra to automate their Shopify accounting.",
    proofQuote1: "We stopped spending 8 hours a month reconciling Shopify payouts. Nxentra does it in seconds.",
    proofRole1: "E-commerce merchant, UAE",
    proofQuote2: "Finally, an accounting system that actually understands how Shopify works. The three-column reconciliation is a game changer.",
    proofRole2: "Bookkeeper, Egypt",
    // Email capture
    earlyAccessTitle: "Get early access",
    earlyAccessSub: "Join the waitlist and be the first to know when new features launch.",
    earlyAccessPlaceholder: "Enter your email",
    earlyAccessCta: "Join waitlist",
    earlyAccessSent: "You're on the list!",
    // FAQ
    faqTitle: "Frequently asked questions",
    faqQ1: "Can I migrate from QuickBooks or Xero?",
    faqA1: "Yes. You can import your existing chart of accounts via CSV. Nxentra maps your account structure and you're up and running in minutes.",
    faqQ2: "How does multi-currency work?",
    faqA2: "Nxentra auto-fetches exchange rates from the ECB daily. Every Shopify order is recorded at the transaction-date rate. Period-end revaluation runs automatically.",
    faqQ3: "Is my financial data safe?",
    faqA3: "Each company gets its own isolated database. All data is encrypted in transit (TLS) and at rest. Every change is logged in an immutable audit trail. You can export all your data anytime.",
    faqQ4: "Do I need to be an accountant to use Nxentra?",
    faqA4: "No. Nxentra auto-creates journal entries from your Shopify orders. If you know what a sale and a refund are, you're good. For advanced features, your accountant can log in with their own role.",
    faqQ5: "What happens after the free trial?",
    faqA5: "You pick a plan that fits. No data is deleted. If you choose not to continue, you can export everything. No lock-in, ever.",
    // Contact
    contactTitle: "Ready to take control?",
    contactSub: "Get in touch and we will set you up in minutes.",
    contactTry: "Try Nxentra free",
    contactEmail: "Email us",
    // Footer
    footer: "Nxentra",
    quickLinks: "Quick links",
    footerRights: "All rights reserved.",
    // Contact Form
    formName: "Your name",
    formEmailPlaceholder: "Email address",
    formMessage: "Tell us about your business...",
    formSend: "Send message",
    formSending: "Sending...",
    formSent: "Message sent! We'll get back to you shortly.",
    formRoleSme: "SME Owner",
    formRoleAccountant: "Accountant",
    formRoleEcommerce: "E-commerce Merchant",
    formRoleInvestor: "Investor",
    formRolePartner: "Partner / Integrator",
  },
  ar: {
    navModules: "الوحدات",
    navWhy: "لماذا Nxentra",
    navHow: "كيف يعمل",
    navPricing: "الأسعار",
    navContact: "تواصل",
    ctaTry: "ابدأ مجاناً",
    ctaLiveDemo: "جرّب العرض التجريبي",
    demoCredentials: "بيانات الدخول — البريد: demo@nxentra.com · كلمة المرور: demo1234",
    ctaDemo: "شاهد العرض",
    heroTag: "محاسبة التجارة الإلكترونية، تلقائياً",
    heroH1a: "متجرك على Shopify يستحق",
    heroH1b: "محاسبة حقيقية.",
    heroSub: "Nxentra يربط Shopify وStripe ونقاط البيع والبنوك في حقيقة مالية واحدة. مطابقة تلقائية. متعدد العملات. جاهز للتدقيق من اليوم الأول.",
    trustFree: "مجاني للبدء",
    trustNoCard: "مسار تدقيق غير قابل للتغيير",
    trustSetup: "بياناتك قابلة للتصدير بالكامل",
    liveOn: "متصل بـ",
    // Shopify Spotlight
    shopifyBadge: "تكامل Shopify",
    shopifyH2a: "تبيع على Shopify؟",
    shopifyH2b: "محاسبتك جاهزة تلقائياً.",
    shopifyDesc: "كل طلب وإرجاع وخصم وضريبة ودفعة من Shopify يتحول تلقائياً إلى قيد يومية مزدوج. تكلفة البضاعة المباعة بالمتوسط المرجح. تحويلات العملات تُعالج تلقائياً. مستويات المخزون متزامنة لحظياً.",
    shopifyBullet1: "الطلبات تُقيَّد تلقائياً في حسابات المبيعات والذمم والضرائب والمخزون",
    shopifyBullet2: "دفعات Shopify تتطابق مع الإيداعات البنكية تلقائياً",
    shopifyBullet3: "المرتجعات تُنشئ قيود عكسية صحيحة — بدون تعديلات يدوية",
    shopifyBullet4: "الطلبات متعددة العملات تُحوَّل بأسعار تاريخ المعاملة",
    shopifyCta: "اربط متجر Shopify الخاص بك",
    shopifyFlow1Label: "طلب Shopify #1042",
    shopifyFlow1Sub: "3 عناصر · $287.50 · USD",
    shopifyFlow2Label: "محرك الاستيعاب",
    shopifyFlow2Sub: "تطبيع ← ربط الحسابات ← تحقق",
    shopifyFlow3Label: "قيد يومية JE-1-000847",
    shopifyFlow3Sub: "مدين ذمم مدينة $287.50 · دائن مبيعات $250.00 · دائن ضريبة $37.50",
    shopifyFlow4Label: "مطابقة تلقائية",
    shopifyFlow4Sub: "تمت المطابقة مع دفعة Shopify #P-2891",
    // Modules
    modulesTitle: "منصة واحدة. كل الوحدات.",
    modulesSub: "توقف عن ربط أدوات منفصلة. Nxentra يعطيك نظام تشغيل كامل لعملك.",
    modAccounting: "المحاسبة",
    modAccountingDesc: "دفتر الأستاذ، دليل الحسابات، قيود اليومية، متعدد العملات، تسوية بنكية",
    modSales: "المبيعات والفواتير",
    modSalesDesc: "فواتير، أكواد ضريبية، ملفات ترحيل، إيصالات عملاء، أعمار الذمم المدينة",
    modInventory: "المخزون",
    modInventoryDesc: "مستودعات، أرصدة مخزون، تتبع تكلفة البضاعة المباعة، المتوسط المرجح",
    modPurchases: "المشتريات",
    modPurchasesDesc: "فواتير شراء، مدفوعات موردين، أعمار الذمم الدائنة، متعدد العملات",
    modProperties: "العقارات",
    modPropertiesDesc: "إدارة الوحدات، عقود إيجار، تحصيل إيجارات، محاسبة المستأجرين",
    modClinic: "العيادة",
    modClinicDesc: "فوترة المرضى، إيرادات المواعيد، مطالبات التأمين، ذمم مدينة طبية",
    modShopify: "مزامنة Shopify",
    modShopifyDesc: "استيعاب تلقائي للطلبات والمرتجعات والدفعات. ربط مالي لحظي.",
    modStripe: "ربط Stripe",
    modStripeDesc: "تسوية مدفوعات، تتبع رسوم، مطابقة دفعات، متعدد العملات",
    // Why Nxentra
    whyTitle: "لماذا ينتقلون إلى Nxentra",
    whySub: "مبني بشكل مختلف عن أنظمة ERP التقليدية. كل معاملة حدث غير قابل للتعديل. كل تقرير مشتق، ليس معدلاً يدوياً.",
    why1Title: "محرك الاستيعاب الشامل",
    why1Desc: "كل طلب ودفعة وإرجاع من أي مصدر يصبح حدثاً مالياً غير قابل للتعديل. Shopify وStripe ونقاط البيع والبنوك — الكل يُطبَّع في دفتر واحد. بدون استيراد CSV. بدون إدخال يدوي. بدون انحراف بيانات.",
    why2Title: "محرك المطابقة التلقائية",
    why2Desc: "Nxentra يطابق المعاملات عبر المصادر تلقائياً. دفعات البنك تتسوى مع طلبات Shopify. رسوم Stripe تطابق قيود اليومية. التباينات تظهر فوراً — ليس في نهاية الشهر عندما يكون الوقت قد فات.",
    why3Title: "مسار تدقيق غير قابل للتغيير",
    why3Desc: "كل رقم في كل تقرير يرجع إلى حدث مصدري. لا شيء يُعدَّل يدوياً. لا شيء يُكتب فوقه. دفاترك ليست دقيقة فقط — بل يمكن إثبات دقتها. المدققون يحبون هذا.",
    why4Title: "متعدد العملات أصلياً",
    why4Desc: "جنيه مصري، دولار، ريال، يورو — الكل في دفتر واحد. أسعار صرف تلقائية، إعادة تقييم العملات، وتتبع الأرباح/الخسائر غير المحققة. مبني للشركات العابرة للحدود.",
    // How It Works
    howTitle: "كيف يعمل",
    howSub: "ثلاث خطوات. خمس دقائق. انتهى.",
    eng1Label: "الخطوة 1",
    eng1Title: "اربط متجر Shopify",
    eng1Desc: "نقرة واحدة للربط. Nxentra يستورد طلباتك ومرتجعاتك ودفعاتك ومنتجاتك تلقائياً. بدون رفع CSV. بدون إدخال يدوي.",
    eng2Label: "الخطوة 2",
    eng2Title: "نُنشئ قيود اليومية لك",
    eng2Desc: "كل طلب يصبح قيد يومية مزدوج صحيح. المبيعات والضرائب والرسوم والمخزون — الكل مربوط بدليل حساباتك تلقائياً.",
    eng3Label: "الخطوة 3",
    eng3Title: "طابق الدفعات فوراً",
    eng3Desc: "شاهد بالضبط كيف تتطابق دفعات Shopify مع إيداعاتك البنكية. عرض ثلاثي الأعمدة: طلبات مقابل دفعات مقابل بنك. التباينات تُرصد فوراً.",
    // Video
    videoTitle: "شاهد Nxentra عملياً",
    videoSub: "شاهد كيف يحول Nxentra البيانات المتفرقة إلى وضوح مالي.",
    // Dashboard Charts
    chartsTitle: "رؤية مالية لحظية",
    chartsSub: "كل رسم بياني مشتق من أحداث حية. الإيرادات والمصروفات والتدفق النقدي ومعدلات المطابقة تتحدث مع تدفق المعاملات.",
    // Stats
    statModules: "وحدات",
    statCurrencies: "عملات مدعومة",
    statEngines: "محركات أساسية",
    statSetup: "وقت الإعداد",
    // Social proof
    proofTitle: "مبني للتجار الذين يطالبون بالدقة",
    proofSub: "تجار الوصول المبكر في الشرق الأوسط وخارجه يستخدمون Nxentra لأتمتة محاسبة Shopify.",
    proofQuote1: "توقفنا عن قضاء 8 ساعات شهرياً في مطابقة دفعات Shopify. Nxentra يفعلها في ثوانٍ.",
    proofRole1: "تاجر إلكتروني، الإمارات",
    proofQuote2: "أخيراً، نظام محاسبة يفهم فعلاً كيف يعمل Shopify. المطابقة ثلاثية الأعمدة غيّرت اللعبة.",
    proofRole2: "محاسب، مصر",
    // Email capture
    earlyAccessTitle: "احصل على وصول مبكر",
    earlyAccessSub: "انضم لقائمة الانتظار وكن أول من يعرف عند إطلاق ميزات جديدة.",
    earlyAccessPlaceholder: "أدخل بريدك الإلكتروني",
    earlyAccessCta: "انضم للقائمة",
    earlyAccessSent: "أنت في القائمة!",
    // FAQ
    faqTitle: "أسئلة شائعة",
    faqQ1: "هل يمكنني الانتقال من QuickBooks أو Xero؟",
    faqA1: "نعم. يمكنك استيراد دليل حساباتك الحالي عبر CSV. Nxentra يربط هيكل حساباتك وتبدأ العمل في دقائق.",
    faqQ2: "كيف يعمل تعدد العملات؟",
    faqA2: "Nxentra يجلب أسعار الصرف من البنك المركزي الأوروبي يومياً. كل طلب Shopify يُسجل بسعر تاريخ المعاملة. إعادة التقييم الدورية تعمل تلقائياً.",
    faqQ3: "هل بياناتي المالية آمنة؟",
    faqA3: "كل شركة لها قاعدة بيانات معزولة. كل البيانات مشفرة أثناء النقل والتخزين. كل تغيير مسجل في مسار تدقيق غير قابل للتعديل. يمكنك تصدير كل بياناتك في أي وقت.",
    faqQ4: "هل أحتاج أن أكون محاسباً لاستخدام Nxentra؟",
    faqA4: "لا. Nxentra يُنشئ قيود اليومية تلقائياً من طلبات Shopify. إذا كنت تعرف ما هو البيع والمرتجع، أنت جاهز. للميزات المتقدمة، محاسبك يمكنه الدخول بدوره الخاص.",
    faqQ5: "ماذا يحدث بعد انتهاء التجربة المجانية؟",
    faqA5: "تختار الخطة المناسبة. لا تُحذف أي بيانات. إذا اخترت عدم المتابعة، يمكنك تصدير كل شيء. بدون احتكار، أبداً.",
    // Pricing
    pricingTitle: "تسعير بسيط وشفاف",
    pricingSub: "ابدأ مجاناً. طوّر عندما تنمو. بدون رسوم مخفية.",
    pricingStarterName: "البداية",
    pricingStarterPrice: "$29",
    pricingStarterPeriod: "/شهر",
    pricingStarterDesc: "لتجار Shopify المستقلين",
    pricingStarterF1: "متجر Shopify واحد",
    pricingStarterF2: "محاسبة أساسية ودفتر أستاذ",
    pricingStarterF3: "تسوية بنكية",
    pricingStarterF4: "مستخدم واحد",
    pricingStarterF5: "دعم بالبريد",
    pricingStarterCta: "ابدأ مجاناً",
    pricingGrowthName: "النمو",
    pricingGrowthPrice: "$79",
    pricingGrowthPeriod: "/شهر",
    pricingGrowthDesc: "للتجار المتناميين",
    pricingGrowthBadge: "الأكثر شعبية",
    pricingGrowthF1: "3 متاجر Shopify",
    pricingGrowthF2: "دعم متعدد العملات",
    pricingGrowthF3: "تسوية التجارة",
    pricingGrowthF4: "5 مستخدمين",
    pricingGrowthF5: "دعم أولوي",
    pricingGrowthF6: "وصول API",
    pricingGrowthCta: "ابدأ مجاناً",
    pricingProName: "احترافي",
    pricingProPrice: "$149",
    pricingProPeriod: "/شهر",
    pricingProDesc: "لمشغلي المتاجر المتعددة",
    pricingProF1: "متاجر غير محدودة",
    pricingProF2: "Stripe + Shopify",
    pricingProF3: "تقارير متقدمة",
    pricingProF4: "15 مستخدم",
    pricingProF5: "دعم مخصص",
    pricingProF6: "تكاملات مخصصة",
    pricingProCta: "تواصل معنا",
    pricingFreeNote: "جميع الخطط تتضمن تجربة مجانية لمدة 14 يوماً. بدون بطاقة ائتمان.",
    // Trust / Security
    trustTitle: "أمان بمستوى البنوك. مدمج.",
    trustSub: "بياناتك المالية تستحق أعلى مستوى حماية. Nxentra مبني بالأمان كأساس، ليس كإضافة.",
    trustSec1Title: "مسار تدقيق غير قابل للتعديل",
    trustSec1Desc: "كل معاملة حدث إضافي فقط. لا يُكتب فوق شيء ولا يُحذف.",
    trustSec2Title: "عزل بيانات المستأجرين",
    trustSec2Desc: "كل شركة لها قاعدة بيانات معزولة. بياناتك لا تختلط أبداً.",
    trustSec3Title: "HTTPS في كل مكان",
    trustSec3Desc: "تشفير TLS، تحميل HSTS مسبق، وسياسة أمان محتوى صارمة.",
    trustSec4Title: "بياناتك قابلة للتصدير",
    trustSec4Desc: "تصدير كامل في أي وقت. بدون احتكار. أنت تملك سجلاتك المالية.",
    trustSec5Title: "صلاحيات حسب الدور",
    trustSec5Desc: "صلاحيات دقيقة لكل مستخدم. مالك، مدير، مستخدم، مشاهد.",
    trustSec6Title: "تسجيل تدقيق مهيكل",
    trustSec6Desc: "كل استدعاء API وتسجيل دخول وتغيير بيانات مسجل بالطوابع الزمنية وسياق المستخدم. مبني للامتثال من اليوم الأول.",
    // Contact
    contactTitle: "مستعد للسيطرة؟",
    contactSub: "تواصل معنا وسنعدك في دقائق.",
    contactTry: "جرب Nxentra مجاناً",
    contactEmail: "راسلنا",
    // Footer
    footer: "Nxentra",
    quickLinks: "روابط سريعة",
    footerRights: "جميع الحقوق محفوظة.",
    // Contact Form
    formName: "اسمك",
    formEmailPlaceholder: "البريد الإلكتروني",
    formMessage: "أخبرنا عن عملك...",
    formSend: "إرسال الرسالة",
    formSending: "جارٍ الإرسال...",
    formSent: "تم إرسال الرسالة! سنتواصل معك قريباً.",
    formRoleSme: "صاحب مشروع صغير",
    formRoleAccountant: "محاسب",
    formRoleEcommerce: "تاجر إلكتروني",
    formRoleInvestor: "مستثمر",
    formRolePartner: "شريك / مُدمج",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  dir: "ltr",
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const stored = localStorage.getItem("nx_lang") as Lang | null;
    if (stored && (stored === "en" || stored === "ar")) {
      setLangState(stored);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("nx_lang", l);
  };

  const t = (key: string) => dict[lang]?.[key] ?? dict.en?.[key] ?? key;
  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
